apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-34-pedido
  labels:
    app: restaurante-34-pedido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurante-34-pedido
  template:
    metadata:
      labels:
        app: restaurante-34-pedido
    spec:
      containers:
        - name: restaurante-34-pedido
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurante-34-pedido
                  key: DATABASE_URL
            - name: MS_PRODUTO_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurante-34-pedido
                  key: MS_PRODUTO_URL
            - name: MS_PAGAMENTO_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurante-34-pedido
                  key: MS_PAGAMENTO_URL
          image: 138684654037.dkr.ecr.us-east-1.amazonaws.com/restaurante-34-pedido:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001

